### ISSUE TITLE
Compact stdout

### ISSUE THREAD

**Issue by jtrakk** [ma-laforge/NumericIO.jl#5]
After reading the readme of this package, I found this post that shows how to make the repl display compactly. Thought you might be interested.

https://discourse.julialang.org/t/compact-float-printing-in-the-repl/4561/9

```jl
julia> sqrt.(1:10)
10-element Vector{Float64}:
 1.0
 1.41421
 1.73205
 2.0
 2.23607
 2.44949
 2.64575
 2.82843
 3.0
 3.16228
```

**Comment by ma-laforge** [comment]
Thanks @jtrakk .

Yes, I have noticed the `IOContext` object as a wrapper for "`::IO`" object --- with user preferences!

I didn't know about this when I first developed NumericIO --- and haven't really figured out the best way to integrate NumericIO into Julia's `print`/`show`/`display`/... system given all the possible avenues to do so.

I mostly wrote this module to get reasonable outputs in [InspectDR](https://github.com/ma-laforge/InspectDR.jl) - and it is working to my satisfaction at the moment. As a consequence:
- I haven't put much thought into improving the user interface/API (though I sincerely think I should).

Though I admit I really like the idea of having a simple, user-definable output format that can somehow augment how numbers are displayed more optimally in different situations/contexts (ex: working with `::IO`s, `::AbstractDisplays`; displaying contents of matrices in a more readable fashion, etc).

### pfitzseb's example
If I'm being honest, I find pfitzseb's example a bit convoluted for what he is trying to achieve:
- The `IOContextDisplay` object expects a `.ctx` FUNCTION that is used to construct an `IOBuffer` to show object `x`.
- All that generic functionality to simply write to `stdout`.
- To me, it would have made more sense for `.ctx` to be a simple `IOContext` wrapper object around `stdout` (instead of a "generator function").

### Comparing to displaying plots
But like I said, Julia's display system makes it possible to do many interesting things wrt displaying numeric values --- the trick is to find a simple, intuitive means to control our output.  I've been dealing with this display problem more actively in the context of displaying plots (either inline, a pop-up GUI, ...):
- Trying to find a simple/straightforward way to save plots with a given width, and aspect ratio.
- And a way to explicitly show the GUI using a function like `displaygui()`, or `inlinedisplay()` when inline images are more appropriate.
- ...because I admit the concept of the display stack (how pfitzseb uses `pushdisplay()`) IS interesting - I'm not 100% convinced it is currently the easiest way to control outputs.

### Future direction
Note that I'm still not certain how I want to move forward with all of this. Many of my display tests (wrt plots) are in my `CMDimData.EasyPlot` module, and I've been experimenting quite a bit in `RSDeltaSigmaPort.jl` (where I have actual goals to achieve with the plots).

I sort of hesitate to modify the current NumericIO API - because I don't have clear direction on how I can improve things (as opposed to making things more convoluted).

If you are interested, I have started to map Julia's display system --- I even generated a graphical call stack of what I found: https://discourse.julialang.org/t/improving-doc-for-display-print-show-repr/69124/3 .

Maybe you will notice something that simplifies how we output numeric values!
